name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    - name: Restore dependencies
      run: dotnet restore PaymentGateway.sln
    - name: Build
      run: dotnet build PaymentGateway.sln --no-restore 
    - name: Test
      run: dotnet test PaymentGateway.sln --no-build --verbosity normal
