name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start dependencies (docker-compose)
      run: |
        docker-compose -f integration-test-db.yml up -d  
    - name: Wait for Postgres Server container
      uses: jakejarvis/wait-action@master
      with:
          time: '5s'
    - name: Generate Migration bundle
      shell: pwsh
      run: |
          cd ./src/PaymentGateway.API
          dotnet ef migrations bundle --self-contained -r ubuntu-x64 -v --force
    - name: Run Migration
      shell: pwsh
      run: |
          ./src/PaymentGateway.API/database_migration.ps1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    - name: Restore dependencies
      run: dotnet restore PaymentGateway.sln
    - name: Build
      run: dotnet build PaymentGateway.sln --no-restore 
    - name: Test
      run: dotnet test PaymentGateway.sln --no-build --verbosity normal
